//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.08.09 at 07:25:26 PM ICT 
//


package com.mt.pos.ws.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for deviceBrand complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="deviceBrand">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="createdDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="deviceBrand" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="idDeviceBrand" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="isActive" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="majorBrand" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "deviceBrand", namespace = "http://rm.isl.mt.com/", propOrder = {
    "createdDateTime",
    "deviceBrand",
    "idDeviceBrand",
    "isActive",
    "majorBrand"
})
public class DeviceBrand {

    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar createdDateTime;
    protected String deviceBrand;
    protected Long idDeviceBrand;
    protected short isActive;
    protected boolean majorBrand;

    /**
     * Gets the value of the createdDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreatedDateTime() {
        return createdDateTime;
    }

    /**
     * Sets the value of the createdDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreatedDateTime(XMLGregorianCalendar value) {
        this.createdDateTime = value;
    }

    /**
     * Gets the value of the deviceBrand property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeviceBrand() {
        return deviceBrand;
    }

    /**
     * Sets the value of the deviceBrand property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeviceBrand(String value) {
        this.deviceBrand = value;
    }

    /**
     * Gets the value of the idDeviceBrand property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getIdDeviceBrand() {
        return idDeviceBrand;
    }

    /**
     * Sets the value of the idDeviceBrand property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setIdDeviceBrand(Long value) {
        this.idDeviceBrand = value;
    }

    /**
     * Gets the value of the isActive property.
     * 
     */
    public short getIsActive() {
        return isActive;
    }

    /**
     * Sets the value of the isActive property.
     * 
     */
    public void setIsActive(short value) {
        this.isActive = value;
    }

    /**
     * Gets the value of the majorBrand property.
     * 
     */
    public boolean isMajorBrand() {
        return majorBrand;
    }

    /**
     * Sets the value of the majorBrand property.
     * 
     */
    public void setMajorBrand(boolean value) {
        this.majorBrand = value;
    }

}
