//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.08.09 at 07:25:26 PM ICT 
//


package com.mt.pos.ws.beans;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.mt.pos.ws.beans package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _NewRegistrationByIccIdAndCellIdFrontImage_QNAME = new QName("", "frontImage");
    private final static QName _NewRegistrationByIccIdAndCellIdBackImage_QNAME = new QName("", "backImage");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.mt.pos.ws.beans
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetRegionsList }
     * 
     */
    public GetRegionsList createGetRegionsList() {
        return new GetRegionsList();
    }

    /**
     * Create an instance of {@link ChangePin }
     * 
     */
    public ChangePin createChangePin() {
        return new ChangePin();
    }

    /**
     * Create an instance of {@link GetRegistrationStatusByMsisdn }
     * 
     */
    public GetRegistrationStatusByMsisdn createGetRegistrationStatusByMsisdn() {
        return new GetRegistrationStatusByMsisdn();
    }

    /**
     * Create an instance of {@link SimSwap }
     * 
     */
    public SimSwap createSimSwap() {
        return new SimSwap();
    }

    /**
     * Create an instance of {@link GetMajorDeviceBrandsList }
     * 
     */
    public GetMajorDeviceBrandsList createGetMajorDeviceBrandsList() {
        return new GetMajorDeviceBrandsList();
    }

    /**
     * Create an instance of {@link TransportKey }
     * 
     */
    public TransportKey createTransportKey() {
        return new TransportKey();
    }

    /**
     * Create an instance of {@link Region }
     * 
     */
    public Region createRegion() {
        return new Region();
    }

    /**
     * Create an instance of {@link SimSms }
     * 
     */
    public SimSms createSimSms() {
        return new SimSms();
    }

    /**
     * Create an instance of {@link GetNumberInventory }
     * 
     */
    public GetNumberInventory createGetNumberInventory() {
        return new GetNumberInventory();
    }

    /**
     * Create an instance of {@link GetSimAppGroupsListResponse }
     * 
     */
    public GetSimAppGroupsListResponse createGetSimAppGroupsListResponse() {
        return new GetSimAppGroupsListResponse();
    }

    /**
     * Create an instance of {@link SimManufacture }
     * 
     */
    public SimManufacture createSimManufacture() {
        return new SimManufacture();
    }

    /**
     * Create an instance of {@link GetDeviceModelsListByIdDeviceBrand }
     * 
     */
    public GetDeviceModelsListByIdDeviceBrand createGetDeviceModelsListByIdDeviceBrand() {
        return new GetDeviceModelsListByIdDeviceBrand();
    }

    /**
     * Create an instance of {@link GetDeviceModelsListByIdDeviceBrandResponse }
     * 
     */
    public GetDeviceModelsListByIdDeviceBrandResponse createGetDeviceModelsListByIdDeviceBrandResponse() {
        return new GetDeviceModelsListByIdDeviceBrandResponse();
    }

    /**
     * Create an instance of {@link SimRecordData }
     * 
     */
    public SimRecordData createSimRecordData() {
        return new SimRecordData();
    }

    /**
     * Create an instance of {@link GetRegistrationStatusByImsi }
     * 
     */
    public GetRegistrationStatusByImsi createGetRegistrationStatusByImsi() {
        return new GetRegistrationStatusByImsi();
    }

    /**
     * Create an instance of {@link GetMajorDeviceBrandsListResponse }
     * 
     */
    public GetMajorDeviceBrandsListResponse createGetMajorDeviceBrandsListResponse() {
        return new GetMajorDeviceBrandsListResponse();
    }

    /**
     * Create an instance of {@link AddSimAppOnSim }
     * 
     */
    public AddSimAppOnSim createAddSimAppOnSim() {
        return new AddSimAppOnSim();
    }

    /**
     * Create an instance of {@link NewRegistrationByIccIdAndCellIdResponse }
     * 
     */
    public NewRegistrationByIccIdAndCellIdResponse createNewRegistrationByIccIdAndCellIdResponse() {
        return new NewRegistrationByIccIdAndCellIdResponse();
    }

    /**
     * Create an instance of {@link AddSimAppOnSimResponse }
     * 
     */
    public AddSimAppOnSimResponse createAddSimAppOnSimResponse() {
        return new AddSimAppOnSimResponse();
    }

    /**
     * Create an instance of {@link GetSidTypesList }
     * 
     */
    public GetSidTypesList createGetSidTypesList() {
        return new GetSidTypesList();
    }

    /**
     * Create an instance of {@link GetSimInfoResponse }
     * 
     */
    public GetSimInfoResponse createGetSimInfoResponse() {
        return new GetSimInfoResponse();
    }

    /**
     * Create an instance of {@link GetStatus }
     * 
     */
    public GetStatus createGetStatus() {
        return new GetStatus();
    }

    /**
     * Create an instance of {@link SimApp }
     * 
     */
    public SimApp createSimApp() {
        return new SimApp();
    }

    /**
     * Create an instance of {@link SimOutputDataPK }
     * 
     */
    public SimOutputDataPK createSimOutputDataPK() {
        return new SimOutputDataPK();
    }

    /**
     * Create an instance of {@link GetRegistrationStatusByMsisdnResponse }
     * 
     */
    public GetRegistrationStatusByMsisdnResponse createGetRegistrationStatusByMsisdnResponse() {
        return new GetRegistrationStatusByMsisdnResponse();
    }

    /**
     * Create an instance of {@link Profile }
     * 
     */
    public Profile createProfile() {
        return new Profile();
    }

    /**
     * Create an instance of {@link SidType }
     * 
     */
    public SidType createSidType() {
        return new SidType();
    }

    /**
     * Create an instance of {@link GetRegistrationStatusByIccIdResponse }
     * 
     */
    public GetRegistrationStatusByIccIdResponse createGetRegistrationStatusByIccIdResponse() {
        return new GetRegistrationStatusByIccIdResponse();
    }

    /**
     * Create an instance of {@link LogoutResponse }
     * 
     */
    public LogoutResponse createLogoutResponse() {
        return new LogoutResponse();
    }

    /**
     * Create an instance of {@link SendMessage }
     * 
     */
    public SendMessage createSendMessage() {
        return new SendMessage();
    }

    /**
     * Create an instance of {@link SimOutputData }
     * 
     */
    public SimOutputData createSimOutputData() {
        return new SimOutputData();
    }

    /**
     * Create an instance of {@link GetSidTypesListResponse }
     * 
     */
    public GetSidTypesListResponse createGetSidTypesListResponse() {
        return new GetSidTypesListResponse();
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link GraphicalProfile }
     * 
     */
    public GraphicalProfile createGraphicalProfile() {
        return new GraphicalProfile();
    }

    /**
     * Create an instance of {@link GetRegistrationStatusByImsiResponse }
     * 
     */
    public GetRegistrationStatusByImsiResponse createGetRegistrationStatusByImsiResponse() {
        return new GetRegistrationStatusByImsiResponse();
    }

    /**
     * Create an instance of {@link SimAppGroup }
     * 
     */
    public SimAppGroup createSimAppGroup() {
        return new SimAppGroup();
    }

    /**
     * Create an instance of {@link SimProduct }
     * 
     */
    public SimProduct createSimProduct() {
        return new SimProduct();
    }

    /**
     * Create an instance of {@link GetSimSmsListResponse }
     * 
     */
    public GetSimSmsListResponse createGetSimSmsListResponse() {
        return new GetSimSmsListResponse();
    }

    /**
     * Create an instance of {@link SimOrder }
     * 
     */
    public SimOrder createSimOrder() {
        return new SimOrder();
    }

    /**
     * Create an instance of {@link GetSimAppsList }
     * 
     */
    public GetSimAppsList createGetSimAppsList() {
        return new GetSimAppsList();
    }

    /**
     * Create an instance of {@link NewRegistrationByIccIdAndCellId }
     * 
     */
    public NewRegistrationByIccIdAndCellId createNewRegistrationByIccIdAndCellId() {
        return new NewRegistrationByIccIdAndCellId();
    }

    /**
     * Create an instance of {@link BackupSimPhoneBooksList }
     * 
     */
    public BackupSimPhoneBooksList createBackupSimPhoneBooksList() {
        return new BackupSimPhoneBooksList();
    }

    /**
     * Create an instance of {@link NewRegistrationByIccId }
     * 
     */
    public NewRegistrationByIccId createNewRegistrationByIccId() {
        return new NewRegistrationByIccId();
    }

    /**
     * Create an instance of {@link RemoveSimAppOnSim }
     * 
     */
    public RemoveSimAppOnSim createRemoveSimAppOnSim() {
        return new RemoveSimAppOnSim();
    }

    /**
     * Create an instance of {@link LogonAndGetInfoNoRegion }
     * 
     */
    public LogonAndGetInfoNoRegion createLogonAndGetInfoNoRegion() {
        return new LogonAndGetInfoNoRegion();
    }

    /**
     * Create an instance of {@link DeviceModel }
     * 
     */
    public DeviceModel createDeviceModel() {
        return new DeviceModel();
    }

    /**
     * Create an instance of {@link GetDeviceBrandsListResponse }
     * 
     */
    public GetDeviceBrandsListResponse createGetDeviceBrandsListResponse() {
        return new GetDeviceBrandsListResponse();
    }

    /**
     * Create an instance of {@link Logout }
     * 
     */
    public Logout createLogout() {
        return new Logout();
    }

    /**
     * Create an instance of {@link LogonResponse }
     * 
     */
    public LogonResponse createLogonResponse() {
        return new LogonResponse();
    }

    /**
     * Create an instance of {@link GetSimAppsListResponse }
     * 
     */
    public GetSimAppsListResponse createGetSimAppsListResponse() {
        return new GetSimAppsListResponse();
    }

    /**
     * Create an instance of {@link GetRegionsListResponse }
     * 
     */
    public GetRegionsListResponse createGetRegionsListResponse() {
        return new GetRegionsListResponse();
    }

    /**
     * Create an instance of {@link ChangePinResponse }
     * 
     */
    public ChangePinResponse createChangePinResponse() {
        return new ChangePinResponse();
    }

    /**
     * Create an instance of {@link GetSimInfo }
     * 
     */
    public GetSimInfo createGetSimInfo() {
        return new GetSimInfo();
    }

    /**
     * Create an instance of {@link TariffPlan }
     * 
     */
    public TariffPlan createTariffPlan() {
        return new TariffPlan();
    }

    /**
     * Create an instance of {@link SimPhoneBook }
     * 
     */
    public SimPhoneBook createSimPhoneBook() {
        return new SimPhoneBook();
    }

    /**
     * Create an instance of {@link GetTariffPlansList }
     * 
     */
    public GetTariffPlansList createGetTariffPlansList() {
        return new GetTariffPlansList();
    }

    /**
     * Create an instance of {@link ProvisioningStatus }
     * 
     */
    public ProvisioningStatus createProvisioningStatus() {
        return new ProvisioningStatus();
    }

    /**
     * Create an instance of {@link NewRegistrationByTImsiAndTMsisdnResponse }
     * 
     */
    public NewRegistrationByTImsiAndTMsisdnResponse createNewRegistrationByTImsiAndTMsisdnResponse() {
        return new NewRegistrationByTImsiAndTMsisdnResponse();
    }

    /**
     * Create an instance of {@link SimManufacturePgp }
     * 
     */
    public SimManufacturePgp createSimManufacturePgp() {
        return new SimManufacturePgp();
    }

    /**
     * Create an instance of {@link GetNumberInventoryByCellId }
     * 
     */
    public GetNumberInventoryByCellId createGetNumberInventoryByCellId() {
        return new GetNumberInventoryByCellId();
    }

    /**
     * Create an instance of {@link GetSimAppGroupsList }
     * 
     */
    public GetSimAppGroupsList createGetSimAppGroupsList() {
        return new GetSimAppGroupsList();
    }

    /**
     * Create an instance of {@link DeviceBrand }
     * 
     */
    public DeviceBrand createDeviceBrand() {
        return new DeviceBrand();
    }

    /**
     * Create an instance of {@link GetStatusResponse }
     * 
     */
    public GetStatusResponse createGetStatusResponse() {
        return new GetStatusResponse();
    }

    /**
     * Create an instance of {@link ServerResponse }
     * 
     */
    public ServerResponse createServerResponse() {
        return new ServerResponse();
    }

    /**
     * Create an instance of {@link LogonAndGetInfo }
     * 
     */
    public LogonAndGetInfo createLogonAndGetInfo() {
        return new LogonAndGetInfo();
    }

    /**
     * Create an instance of {@link SimRecordDataPK }
     * 
     */
    public SimRecordDataPK createSimRecordDataPK() {
        return new SimRecordDataPK();
    }

    /**
     * Create an instance of {@link GetDeviceBrandsList }
     * 
     */
    public GetDeviceBrandsList createGetDeviceBrandsList() {
        return new GetDeviceBrandsList();
    }

    /**
     * Create an instance of {@link GetSimPhoneBookList }
     * 
     */
    public GetSimPhoneBookList createGetSimPhoneBookList() {
        return new GetSimPhoneBookList();
    }

    /**
     * Create an instance of {@link GetSimSmsList }
     * 
     */
    public GetSimSmsList createGetSimSmsList() {
        return new GetSimSmsList();
    }

    /**
     * Create an instance of {@link RemoveSimAppOnSimResponse }
     * 
     */
    public RemoveSimAppOnSimResponse createRemoveSimAppOnSimResponse() {
        return new RemoveSimAppOnSimResponse();
    }

    /**
     * Create an instance of {@link GetNumberInventoryResponse }
     * 
     */
    public GetNumberInventoryResponse createGetNumberInventoryResponse() {
        return new GetNumberInventoryResponse();
    }

    /**
     * Create an instance of {@link TransportKeyAlgorithm }
     * 
     */
    public TransportKeyAlgorithm createTransportKeyAlgorithm() {
        return new TransportKeyAlgorithm();
    }

    /**
     * Create an instance of {@link GetSimPhoneBookListResponse }
     * 
     */
    public GetSimPhoneBookListResponse createGetSimPhoneBookListResponse() {
        return new GetSimPhoneBookListResponse();
    }

    /**
     * Create an instance of {@link LogonAndGetInfoNoRegionResponse }
     * 
     */
    public LogonAndGetInfoNoRegionResponse createLogonAndGetInfoNoRegionResponse() {
        return new LogonAndGetInfoNoRegionResponse();
    }

    /**
     * Create an instance of {@link OrderLineItem }
     * 
     */
    public OrderLineItem createOrderLineItem() {
        return new OrderLineItem();
    }

    /**
     * Create an instance of {@link BackupSimSmsList }
     * 
     */
    public BackupSimSmsList createBackupSimSmsList() {
        return new BackupSimSmsList();
    }

    /**
     * Create an instance of {@link BackupSimSmsListResponse }
     * 
     */
    public BackupSimSmsListResponse createBackupSimSmsListResponse() {
        return new BackupSimSmsListResponse();
    }

    /**
     * Create an instance of {@link NewRegistrationByIccIdResponse }
     * 
     */
    public NewRegistrationByIccIdResponse createNewRegistrationByIccIdResponse() {
        return new NewRegistrationByIccIdResponse();
    }

    /**
     * Create an instance of {@link GetTariffPlansListResponse }
     * 
     */
    public GetTariffPlansListResponse createGetTariffPlansListResponse() {
        return new GetTariffPlansListResponse();
    }

    /**
     * Create an instance of {@link LogonAndGetInfoResponse }
     * 
     */
    public LogonAndGetInfoResponse createLogonAndGetInfoResponse() {
        return new LogonAndGetInfoResponse();
    }

    /**
     * Create an instance of {@link ElectricalProfile }
     * 
     */
    public ElectricalProfile createElectricalProfile() {
        return new ElectricalProfile();
    }

    /**
     * Create an instance of {@link Company }
     * 
     */
    public Company createCompany() {
        return new Company();
    }

    /**
     * Create an instance of {@link GetRegistrationStatusByIccId }
     * 
     */
    public GetRegistrationStatusByIccId createGetRegistrationStatusByIccId() {
        return new GetRegistrationStatusByIccId();
    }

    /**
     * Create an instance of {@link Logon }
     * 
     */
    public Logon createLogon() {
        return new Logon();
    }

    /**
     * Create an instance of {@link WhitePaper }
     * 
     */
    public WhitePaper createWhitePaper() {
        return new WhitePaper();
    }

    /**
     * Create an instance of {@link BackupSimPhoneBooksListResponse }
     * 
     */
    public BackupSimPhoneBooksListResponse createBackupSimPhoneBooksListResponse() {
        return new BackupSimPhoneBooksListResponse();
    }

    /**
     * Create an instance of {@link OrderInputFile }
     * 
     */
    public OrderInputFile createOrderInputFile() {
        return new OrderInputFile();
    }

    /**
     * Create an instance of {@link SendMessageResponse }
     * 
     */
    public SendMessageResponse createSendMessageResponse() {
        return new SendMessageResponse();
    }

    /**
     * Create an instance of {@link OrderOutputFile }
     * 
     */
    public OrderOutputFile createOrderOutputFile() {
        return new OrderOutputFile();
    }

    /**
     * Create an instance of {@link GetNumberInventoryByCellIdResponse }
     * 
     */
    public GetNumberInventoryByCellIdResponse createGetNumberInventoryByCellIdResponse() {
        return new GetNumberInventoryByCellIdResponse();
    }

    /**
     * Create an instance of {@link SimSwapResponse }
     * 
     */
    public SimSwapResponse createSimSwapResponse() {
        return new SimSwapResponse();
    }

    /**
     * Create an instance of {@link NewRegistrationByTImsiAndTMsisdn }
     * 
     */
    public NewRegistrationByTImsiAndTMsisdn createNewRegistrationByTImsiAndTMsisdn() {
        return new NewRegistrationByTImsiAndTMsisdn();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "frontImage", scope = NewRegistrationByIccIdAndCellId.class)
    public JAXBElement<byte[]> createNewRegistrationByIccIdAndCellIdFrontImage(byte[] value) {
        return new JAXBElement<byte[]>(_NewRegistrationByIccIdAndCellIdFrontImage_QNAME, byte[].class, NewRegistrationByIccIdAndCellId.class, ((byte[]) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "backImage", scope = NewRegistrationByIccIdAndCellId.class)
    public JAXBElement<byte[]> createNewRegistrationByIccIdAndCellIdBackImage(byte[] value) {
        return new JAXBElement<byte[]>(_NewRegistrationByIccIdAndCellIdBackImage_QNAME, byte[].class, NewRegistrationByIccIdAndCellId.class, ((byte[]) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "frontImage", scope = NewRegistrationByTImsiAndTMsisdn.class)
    public JAXBElement<byte[]> createNewRegistrationByTImsiAndTMsisdnFrontImage(byte[] value) {
        return new JAXBElement<byte[]>(_NewRegistrationByIccIdAndCellIdFrontImage_QNAME, byte[].class, NewRegistrationByTImsiAndTMsisdn.class, ((byte[]) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "backImage", scope = NewRegistrationByTImsiAndTMsisdn.class)
    public JAXBElement<byte[]> createNewRegistrationByTImsiAndTMsisdnBackImage(byte[] value) {
        return new JAXBElement<byte[]>(_NewRegistrationByIccIdAndCellIdBackImage_QNAME, byte[].class, NewRegistrationByTImsiAndTMsisdn.class, ((byte[]) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "frontImage", scope = NewRegistrationByIccId.class)
    public JAXBElement<byte[]> createNewRegistrationByIccIdFrontImage(byte[] value) {
        return new JAXBElement<byte[]>(_NewRegistrationByIccIdAndCellIdFrontImage_QNAME, byte[].class, NewRegistrationByIccId.class, ((byte[]) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "backImage", scope = NewRegistrationByIccId.class)
    public JAXBElement<byte[]> createNewRegistrationByIccIdBackImage(byte[] value) {
        return new JAXBElement<byte[]>(_NewRegistrationByIccIdAndCellIdBackImage_QNAME, byte[].class, NewRegistrationByIccId.class, ((byte[]) value));
    }

}
