//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.08.09 at 07:25:26 PM ICT 
//


package com.mt.pos.ws.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for provisioningStatus complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="provisioningStatus">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="idProvisioningStatus" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="provisioningStatusDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="provisioningStatusName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "provisioningStatus", namespace = "http://rm.isl.mt.com/", propOrder = {
    "idProvisioningStatus",
    "provisioningStatusDescription",
    "provisioningStatusName"
})
public class ProvisioningStatus {

    protected Integer idProvisioningStatus;
    protected String provisioningStatusDescription;
    protected String provisioningStatusName;

    /**
     * Gets the value of the idProvisioningStatus property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getIdProvisioningStatus() {
        return idProvisioningStatus;
    }

    /**
     * Sets the value of the idProvisioningStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setIdProvisioningStatus(Integer value) {
        this.idProvisioningStatus = value;
    }

    /**
     * Gets the value of the provisioningStatusDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProvisioningStatusDescription() {
        return provisioningStatusDescription;
    }

    /**
     * Sets the value of the provisioningStatusDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProvisioningStatusDescription(String value) {
        this.provisioningStatusDescription = value;
    }

    /**
     * Gets the value of the provisioningStatusName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProvisioningStatusName() {
        return provisioningStatusName;
    }

    /**
     * Sets the value of the provisioningStatusName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProvisioningStatusName(String value) {
        this.provisioningStatusName = value;
    }

}
