//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.08.09 at 07:25:26 PM ICT 
//


package com.mt.pos.ws.beans;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for simApp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="simApp">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="company" type="{http://rm.isl.mt.com/}company" minOccurs="0"/>
 *         &lt;element name="createdDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="idSimApp" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="isActive" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="profileCollection" type="{http://rm.isl.mt.com/}profile" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="simAppCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="simAppData" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/>
 *         &lt;element name="simAppDataName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="simAppDesc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="simAppDlPrice" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="simAppFile" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="simAppGroupCollection" type="{http://rm.isl.mt.com/}simAppGroup" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="simAppHeader" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/>
 *         &lt;element name="simAppHeaderName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="simAppImg" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/>
 *         &lt;element name="simAppImgName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="simAppName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="simAppSize" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="simAppUsePrice" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="simAppVersion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="updatedDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "simApp", namespace = "http://rm.isl.mt.com/", propOrder = {
    "company",
    "createdDateTime",
    "idSimApp",
    "isActive",
    "profileCollections",
    "simAppCode",
    "simAppData",
    "simAppDataName",
    "simAppDesc",
    "simAppDlPrice",
    "simAppFile",
    "simAppGroupCollections",
    "simAppHeader",
    "simAppHeaderName",
    "simAppImg",
    "simAppImgName",
    "simAppName",
    "simAppSize",
    "simAppUsePrice",
    "simAppVersion",
    "updatedDateTime"
})
public class SimApp {

    protected Company company;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar createdDateTime;
    protected Integer idSimApp;
    protected boolean isActive;
    @XmlElement(name = "profileCollection", nillable = true)
    protected List<Profile> profileCollections;
    protected String simAppCode;
    protected byte[] simAppData;
    protected String simAppDataName;
    protected String simAppDesc;
    protected BigDecimal simAppDlPrice;
    protected String simAppFile;
    @XmlElement(name = "simAppGroupCollection", nillable = true)
    protected List<SimAppGroup> simAppGroupCollections;
    protected byte[] simAppHeader;
    protected String simAppHeaderName;
    protected byte[] simAppImg;
    protected String simAppImgName;
    protected String simAppName;
    protected Long simAppSize;
    protected BigDecimal simAppUsePrice;
    protected String simAppVersion;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar updatedDateTime;

    /**
     * Gets the value of the company property.
     * 
     * @return
     *     possible object is
     *     {@link Company }
     *     
     */
    public Company getCompany() {
        return company;
    }

    /**
     * Sets the value of the company property.
     * 
     * @param value
     *     allowed object is
     *     {@link Company }
     *     
     */
    public void setCompany(Company value) {
        this.company = value;
    }

    /**
     * Gets the value of the createdDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreatedDateTime() {
        return createdDateTime;
    }

    /**
     * Sets the value of the createdDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreatedDateTime(XMLGregorianCalendar value) {
        this.createdDateTime = value;
    }

    /**
     * Gets the value of the idSimApp property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getIdSimApp() {
        return idSimApp;
    }

    /**
     * Sets the value of the idSimApp property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setIdSimApp(Integer value) {
        this.idSimApp = value;
    }

    /**
     * Gets the value of the isActive property.
     * 
     */
    public boolean isIsActive() {
        return isActive;
    }

    /**
     * Sets the value of the isActive property.
     * 
     */
    public void setIsActive(boolean value) {
        this.isActive = value;
    }

    /**
     * Gets the value of the profileCollections property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the profileCollections property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProfileCollections().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Profile }
     * 
     * 
     */
    public List<Profile> getProfileCollections() {
        if (profileCollections == null) {
            profileCollections = new ArrayList<Profile>();
        }
        return this.profileCollections;
    }

    /**
     * Gets the value of the simAppCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSimAppCode() {
        return simAppCode;
    }

    /**
     * Sets the value of the simAppCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSimAppCode(String value) {
        this.simAppCode = value;
    }

    /**
     * Gets the value of the simAppData property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getSimAppData() {
        return simAppData;
    }

    /**
     * Sets the value of the simAppData property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setSimAppData(byte[] value) {
        this.simAppData = ((byte[]) value);
    }

    /**
     * Gets the value of the simAppDataName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSimAppDataName() {
        return simAppDataName;
    }

    /**
     * Sets the value of the simAppDataName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSimAppDataName(String value) {
        this.simAppDataName = value;
    }

    /**
     * Gets the value of the simAppDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSimAppDesc() {
        return simAppDesc;
    }

    /**
     * Sets the value of the simAppDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSimAppDesc(String value) {
        this.simAppDesc = value;
    }

    /**
     * Gets the value of the simAppDlPrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSimAppDlPrice() {
        return simAppDlPrice;
    }

    /**
     * Sets the value of the simAppDlPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSimAppDlPrice(BigDecimal value) {
        this.simAppDlPrice = value;
    }

    /**
     * Gets the value of the simAppFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSimAppFile() {
        return simAppFile;
    }

    /**
     * Sets the value of the simAppFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSimAppFile(String value) {
        this.simAppFile = value;
    }

    /**
     * Gets the value of the simAppGroupCollections property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the simAppGroupCollections property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSimAppGroupCollections().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SimAppGroup }
     * 
     * 
     */
    public List<SimAppGroup> getSimAppGroupCollections() {
        if (simAppGroupCollections == null) {
            simAppGroupCollections = new ArrayList<SimAppGroup>();
        }
        return this.simAppGroupCollections;
    }

    /**
     * Gets the value of the simAppHeader property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getSimAppHeader() {
        return simAppHeader;
    }

    /**
     * Sets the value of the simAppHeader property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setSimAppHeader(byte[] value) {
        this.simAppHeader = ((byte[]) value);
    }

    /**
     * Gets the value of the simAppHeaderName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSimAppHeaderName() {
        return simAppHeaderName;
    }

    /**
     * Sets the value of the simAppHeaderName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSimAppHeaderName(String value) {
        this.simAppHeaderName = value;
    }

    /**
     * Gets the value of the simAppImg property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getSimAppImg() {
        return simAppImg;
    }

    /**
     * Sets the value of the simAppImg property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setSimAppImg(byte[] value) {
        this.simAppImg = ((byte[]) value);
    }

    /**
     * Gets the value of the simAppImgName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSimAppImgName() {
        return simAppImgName;
    }

    /**
     * Sets the value of the simAppImgName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSimAppImgName(String value) {
        this.simAppImgName = value;
    }

    /**
     * Gets the value of the simAppName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSimAppName() {
        return simAppName;
    }

    /**
     * Sets the value of the simAppName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSimAppName(String value) {
        this.simAppName = value;
    }

    /**
     * Gets the value of the simAppSize property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getSimAppSize() {
        return simAppSize;
    }

    /**
     * Sets the value of the simAppSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setSimAppSize(Long value) {
        this.simAppSize = value;
    }

    /**
     * Gets the value of the simAppUsePrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSimAppUsePrice() {
        return simAppUsePrice;
    }

    /**
     * Sets the value of the simAppUsePrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSimAppUsePrice(BigDecimal value) {
        this.simAppUsePrice = value;
    }

    /**
     * Gets the value of the simAppVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSimAppVersion() {
        return simAppVersion;
    }

    /**
     * Sets the value of the simAppVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSimAppVersion(String value) {
        this.simAppVersion = value;
    }

    /**
     * Gets the value of the updatedDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getUpdatedDateTime() {
        return updatedDateTime;
    }

    /**
     * Sets the value of the updatedDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setUpdatedDateTime(XMLGregorianCalendar value) {
        this.updatedDateTime = value;
    }

}
