//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.08.09 at 07:25:26 PM ICT 
//


package com.mt.pos.ws.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for simOrder complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="simOrder">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="batch" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="idPgpKey" type="{http://rm.isl.mt.com/}simManufacturePgp" minOccurs="0"/>
 *         &lt;element name="idSimOrder" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="orderNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="orderTimeStamp" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="simManufacture" type="{http://rm.isl.mt.com/}simManufacture" minOccurs="0"/>
 *         &lt;element name="user" type="{http://rm.isl.mt.com/}user" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "simOrder", namespace = "http://rm.isl.mt.com/", propOrder = {
    "batch",
    "idPgpKey",
    "idSimOrder",
    "orderNumber",
    "orderTimeStamp",
    "simManufacture",
    "user"
})
public class SimOrder {

    protected Integer batch;
    protected SimManufacturePgp idPgpKey;
    protected Integer idSimOrder;
    protected String orderNumber;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar orderTimeStamp;
    protected SimManufacture simManufacture;
    protected User user;

    /**
     * Gets the value of the batch property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getBatch() {
        return batch;
    }

    /**
     * Sets the value of the batch property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setBatch(Integer value) {
        this.batch = value;
    }

    /**
     * Gets the value of the idPgpKey property.
     * 
     * @return
     *     possible object is
     *     {@link SimManufacturePgp }
     *     
     */
    public SimManufacturePgp getIdPgpKey() {
        return idPgpKey;
    }

    /**
     * Sets the value of the idPgpKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimManufacturePgp }
     *     
     */
    public void setIdPgpKey(SimManufacturePgp value) {
        this.idPgpKey = value;
    }

    /**
     * Gets the value of the idSimOrder property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getIdSimOrder() {
        return idSimOrder;
    }

    /**
     * Sets the value of the idSimOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setIdSimOrder(Integer value) {
        this.idSimOrder = value;
    }

    /**
     * Gets the value of the orderNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderNumber() {
        return orderNumber;
    }

    /**
     * Sets the value of the orderNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderNumber(String value) {
        this.orderNumber = value;
    }

    /**
     * Gets the value of the orderTimeStamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOrderTimeStamp() {
        return orderTimeStamp;
    }

    /**
     * Sets the value of the orderTimeStamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOrderTimeStamp(XMLGregorianCalendar value) {
        this.orderTimeStamp = value;
    }

    /**
     * Gets the value of the simManufacture property.
     * 
     * @return
     *     possible object is
     *     {@link SimManufacture }
     *     
     */
    public SimManufacture getSimManufacture() {
        return simManufacture;
    }

    /**
     * Sets the value of the simManufacture property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimManufacture }
     *     
     */
    public void setSimManufacture(SimManufacture value) {
        this.simManufacture = value;
    }

    /**
     * Gets the value of the user property.
     * 
     * @return
     *     possible object is
     *     {@link User }
     *     
     */
    public User getUser() {
        return user;
    }

    /**
     * Sets the value of the user property.
     * 
     * @param value
     *     allowed object is
     *     {@link User }
     *     
     */
    public void setUser(User value) {
        this.user = value;
    }

}
