//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.08.09 at 07:25:26 PM ICT 
//


package com.mt.pos.ws.beans;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for simRecordData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="simRecordData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="availableMemory" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="company" type="{http://rm.isl.mt.com/}company" minOccurs="0"/>
 *         &lt;element name="lastBackup" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="orderInputFile" type="{http://rm.isl.mt.com/}orderInputFile" minOccurs="0"/>
 *         &lt;element name="simAppCollection" type="{http://rm.isl.mt.com/}simApp" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="simImsi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="simMsisdn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="simRecordDataPK" type="{http://rm.isl.mt.com/}simRecordDataPK" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "simRecordData", namespace = "http://rm.isl.mt.com/", propOrder = {
    "availableMemory",
    "company",
    "lastBackup",
    "orderInputFile",
    "simAppCollections",
    "simImsi",
    "simMsisdn",
    "simRecordDataPK"
})
public class SimRecordData {

    protected Long availableMemory;
    protected Company company;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastBackup;
    protected OrderInputFile orderInputFile;
    @XmlElement(name = "simAppCollection", nillable = true)
    protected List<SimApp> simAppCollections;
    protected String simImsi;
    protected String simMsisdn;
    protected SimRecordDataPK simRecordDataPK;

    /**
     * Gets the value of the availableMemory property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getAvailableMemory() {
        return availableMemory;
    }

    /**
     * Sets the value of the availableMemory property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setAvailableMemory(Long value) {
        this.availableMemory = value;
    }

    /**
     * Gets the value of the company property.
     * 
     * @return
     *     possible object is
     *     {@link Company }
     *     
     */
    public Company getCompany() {
        return company;
    }

    /**
     * Sets the value of the company property.
     * 
     * @param value
     *     allowed object is
     *     {@link Company }
     *     
     */
    public void setCompany(Company value) {
        this.company = value;
    }

    /**
     * Gets the value of the lastBackup property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastBackup() {
        return lastBackup;
    }

    /**
     * Sets the value of the lastBackup property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastBackup(XMLGregorianCalendar value) {
        this.lastBackup = value;
    }

    /**
     * Gets the value of the orderInputFile property.
     * 
     * @return
     *     possible object is
     *     {@link OrderInputFile }
     *     
     */
    public OrderInputFile getOrderInputFile() {
        return orderInputFile;
    }

    /**
     * Sets the value of the orderInputFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderInputFile }
     *     
     */
    public void setOrderInputFile(OrderInputFile value) {
        this.orderInputFile = value;
    }

    /**
     * Gets the value of the simAppCollections property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the simAppCollections property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSimAppCollections().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SimApp }
     * 
     * 
     */
    public List<SimApp> getSimAppCollections() {
        if (simAppCollections == null) {
            simAppCollections = new ArrayList<SimApp>();
        }
        return this.simAppCollections;
    }

    /**
     * Gets the value of the simImsi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSimImsi() {
        return simImsi;
    }

    /**
     * Sets the value of the simImsi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSimImsi(String value) {
        this.simImsi = value;
    }

    /**
     * Gets the value of the simMsisdn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSimMsisdn() {
        return simMsisdn;
    }

    /**
     * Sets the value of the simMsisdn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSimMsisdn(String value) {
        this.simMsisdn = value;
    }

    /**
     * Gets the value of the simRecordDataPK property.
     * 
     * @return
     *     possible object is
     *     {@link SimRecordDataPK }
     *     
     */
    public SimRecordDataPK getSimRecordDataPK() {
        return simRecordDataPK;
    }

    /**
     * Sets the value of the simRecordDataPK property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimRecordDataPK }
     *     
     */
    public void setSimRecordDataPK(SimRecordDataPK value) {
        this.simRecordDataPK = value;
    }

}
