//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.08.09 at 07:25:26 PM ICT 
//


package com.mt.pos.ws.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for transportKey complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="transportKey">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="company" type="{http://rm.isl.mt.com/}company" minOccurs="0"/>
 *         &lt;element name="idTransportKey" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="transportKeyAlgorithm" type="{http://rm.isl.mt.com/}transportKeyAlgorithm" minOccurs="0"/>
 *         &lt;element name="transportKeyLabel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="transportKeyNumber" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="transportKeyValue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "transportKey", namespace = "http://rm.isl.mt.com/", propOrder = {
    "company",
    "idTransportKey",
    "transportKeyAlgorithm",
    "transportKeyLabel",
    "transportKeyNumber",
    "transportKeyValue"
})
public class TransportKey {

    protected Company company;
    protected Integer idTransportKey;
    protected TransportKeyAlgorithm transportKeyAlgorithm;
    protected String transportKeyLabel;
    protected Integer transportKeyNumber;
    protected String transportKeyValue;

    /**
     * Gets the value of the company property.
     * 
     * @return
     *     possible object is
     *     {@link Company }
     *     
     */
    public Company getCompany() {
        return company;
    }

    /**
     * Sets the value of the company property.
     * 
     * @param value
     *     allowed object is
     *     {@link Company }
     *     
     */
    public void setCompany(Company value) {
        this.company = value;
    }

    /**
     * Gets the value of the idTransportKey property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getIdTransportKey() {
        return idTransportKey;
    }

    /**
     * Sets the value of the idTransportKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setIdTransportKey(Integer value) {
        this.idTransportKey = value;
    }

    /**
     * Gets the value of the transportKeyAlgorithm property.
     * 
     * @return
     *     possible object is
     *     {@link TransportKeyAlgorithm }
     *     
     */
    public TransportKeyAlgorithm getTransportKeyAlgorithm() {
        return transportKeyAlgorithm;
    }

    /**
     * Sets the value of the transportKeyAlgorithm property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransportKeyAlgorithm }
     *     
     */
    public void setTransportKeyAlgorithm(TransportKeyAlgorithm value) {
        this.transportKeyAlgorithm = value;
    }

    /**
     * Gets the value of the transportKeyLabel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransportKeyLabel() {
        return transportKeyLabel;
    }

    /**
     * Sets the value of the transportKeyLabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransportKeyLabel(String value) {
        this.transportKeyLabel = value;
    }

    /**
     * Gets the value of the transportKeyNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTransportKeyNumber() {
        return transportKeyNumber;
    }

    /**
     * Sets the value of the transportKeyNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTransportKeyNumber(Integer value) {
        this.transportKeyNumber = value;
    }

    /**
     * Gets the value of the transportKeyValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransportKeyValue() {
        return transportKeyValue;
    }

    /**
     * Sets the value of the transportKeyValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransportKeyValue(String value) {
        this.transportKeyValue = value;
    }

}
