//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.08.09 at 07:25:26 PM ICT 
//


package com.mt.pos.ws.beans;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for backupSimSmsList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="backupSimSmsList">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="securityToken" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="idSimIcc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="simSmsList" type="{http://rm.isl.mt.com/}simSms" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "backupSimSmsList", namespace = "http://rm.isl.mt.com/", propOrder = {
    "securityToken",
    "idSimIcc",
    "simSmsLists"
})
@XmlRootElement(name = "backupSimSmsList", namespace = "http://rm.isl.mt.com/")
public class BackupSimSmsList {

    protected String securityToken;
    protected String idSimIcc;
    @XmlElement(name = "simSmsList")
    protected List<SimSms> simSmsLists;

    /**
     * Gets the value of the securityToken property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecurityToken() {
        return securityToken;
    }

    /**
     * Sets the value of the securityToken property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecurityToken(String value) {
        this.securityToken = value;
    }

    /**
     * Gets the value of the idSimIcc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdSimIcc() {
        return idSimIcc;
    }

    /**
     * Sets the value of the idSimIcc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdSimIcc(String value) {
        this.idSimIcc = value;
    }

    /**
     * Gets the value of the simSmsLists property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the simSmsLists property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSimSmsLists().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SimSms }
     * 
     * 
     */
    public List<SimSms> getSimSmsLists() {
        if (simSmsLists == null) {
            simSmsLists = new ArrayList<SimSms>();
        }
        return this.simSmsLists;
    }

}
