//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.08.09 at 07:25:26 PM ICT 
//


package com.mt.pos.ws.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for electricalProfile complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="electricalProfile">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="electricalProfileDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="electricalProfileNumber" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="idElectricalProfile" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="whitePaper" type="{http://rm.isl.mt.com/}whitePaper" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "electricalProfile", namespace = "http://rm.isl.mt.com/", propOrder = {
    "electricalProfileDescription",
    "electricalProfileNumber",
    "idElectricalProfile",
    "whitePaper"
})
public class ElectricalProfile {

    protected String electricalProfileDescription;
    protected Long electricalProfileNumber;
    protected Integer idElectricalProfile;
    protected WhitePaper whitePaper;

    /**
     * Gets the value of the electricalProfileDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getElectricalProfileDescription() {
        return electricalProfileDescription;
    }

    /**
     * Sets the value of the electricalProfileDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setElectricalProfileDescription(String value) {
        this.electricalProfileDescription = value;
    }

    /**
     * Gets the value of the electricalProfileNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getElectricalProfileNumber() {
        return electricalProfileNumber;
    }

    /**
     * Sets the value of the electricalProfileNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setElectricalProfileNumber(Long value) {
        this.electricalProfileNumber = value;
    }

    /**
     * Gets the value of the idElectricalProfile property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getIdElectricalProfile() {
        return idElectricalProfile;
    }

    /**
     * Sets the value of the idElectricalProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setIdElectricalProfile(Integer value) {
        this.idElectricalProfile = value;
    }

    /**
     * Gets the value of the whitePaper property.
     * 
     * @return
     *     possible object is
     *     {@link WhitePaper }
     *     
     */
    public WhitePaper getWhitePaper() {
        return whitePaper;
    }

    /**
     * Sets the value of the whitePaper property.
     * 
     * @param value
     *     allowed object is
     *     {@link WhitePaper }
     *     
     */
    public void setWhitePaper(WhitePaper value) {
        this.whitePaper = value;
    }

}
