//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.08.09 at 07:25:26 PM ICT 
//


package com.mt.pos.ws.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for graphicalProfile complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="graphicalProfile">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="graphicalProfileDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="graphicalProfileNumber" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="idGraphicalProfile" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="whitePaper" type="{http://rm.isl.mt.com/}whitePaper" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "graphicalProfile", namespace = "http://rm.isl.mt.com/", propOrder = {
    "graphicalProfileDescription",
    "graphicalProfileNumber",
    "idGraphicalProfile",
    "whitePaper"
})
public class GraphicalProfile {

    protected String graphicalProfileDescription;
    protected Long graphicalProfileNumber;
    protected Integer idGraphicalProfile;
    protected WhitePaper whitePaper;

    /**
     * Gets the value of the graphicalProfileDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGraphicalProfileDescription() {
        return graphicalProfileDescription;
    }

    /**
     * Sets the value of the graphicalProfileDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGraphicalProfileDescription(String value) {
        this.graphicalProfileDescription = value;
    }

    /**
     * Gets the value of the graphicalProfileNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getGraphicalProfileNumber() {
        return graphicalProfileNumber;
    }

    /**
     * Sets the value of the graphicalProfileNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setGraphicalProfileNumber(Long value) {
        this.graphicalProfileNumber = value;
    }

    /**
     * Gets the value of the idGraphicalProfile property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getIdGraphicalProfile() {
        return idGraphicalProfile;
    }

    /**
     * Sets the value of the idGraphicalProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setIdGraphicalProfile(Integer value) {
        this.idGraphicalProfile = value;
    }

    /**
     * Gets the value of the whitePaper property.
     * 
     * @return
     *     possible object is
     *     {@link WhitePaper }
     *     
     */
    public WhitePaper getWhitePaper() {
        return whitePaper;
    }

    /**
     * Sets the value of the whitePaper property.
     * 
     * @param value
     *     allowed object is
     *     {@link WhitePaper }
     *     
     */
    public void setWhitePaper(WhitePaper value) {
        this.whitePaper = value;
    }

}
