//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.08.09 at 07:25:26 PM ICT 
//


package com.mt.pos.ws.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for orderOutputFile complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="orderOutputFile">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="company" type="{http://rm.isl.mt.com/}company" minOccurs="0"/>
 *         &lt;element name="fileLocation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fileName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="idOrderOutputFile" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="orderLineItem" type="{http://rm.isl.mt.com/}orderLineItem" minOccurs="0"/>
 *         &lt;element name="provisioningStatus" type="{http://rm.isl.mt.com/}provisioningStatus" minOccurs="0"/>
 *         &lt;element name="recordQuantity" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="timeStampReceived" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "orderOutputFile", namespace = "http://rm.isl.mt.com/", propOrder = {
    "company",
    "fileLocation",
    "fileName",
    "idOrderOutputFile",
    "orderLineItem",
    "provisioningStatus",
    "recordQuantity",
    "timeStampReceived"
})
public class OrderOutputFile {

    protected Company company;
    protected String fileLocation;
    protected String fileName;
    protected Integer idOrderOutputFile;
    protected OrderLineItem orderLineItem;
    protected ProvisioningStatus provisioningStatus;
    protected Integer recordQuantity;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timeStampReceived;

    /**
     * Gets the value of the company property.
     * 
     * @return
     *     possible object is
     *     {@link Company }
     *     
     */
    public Company getCompany() {
        return company;
    }

    /**
     * Sets the value of the company property.
     * 
     * @param value
     *     allowed object is
     *     {@link Company }
     *     
     */
    public void setCompany(Company value) {
        this.company = value;
    }

    /**
     * Gets the value of the fileLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileLocation() {
        return fileLocation;
    }

    /**
     * Sets the value of the fileLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileLocation(String value) {
        this.fileLocation = value;
    }

    /**
     * Gets the value of the fileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * Sets the value of the fileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileName(String value) {
        this.fileName = value;
    }

    /**
     * Gets the value of the idOrderOutputFile property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getIdOrderOutputFile() {
        return idOrderOutputFile;
    }

    /**
     * Sets the value of the idOrderOutputFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setIdOrderOutputFile(Integer value) {
        this.idOrderOutputFile = value;
    }

    /**
     * Gets the value of the orderLineItem property.
     * 
     * @return
     *     possible object is
     *     {@link OrderLineItem }
     *     
     */
    public OrderLineItem getOrderLineItem() {
        return orderLineItem;
    }

    /**
     * Sets the value of the orderLineItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderLineItem }
     *     
     */
    public void setOrderLineItem(OrderLineItem value) {
        this.orderLineItem = value;
    }

    /**
     * Gets the value of the provisioningStatus property.
     * 
     * @return
     *     possible object is
     *     {@link ProvisioningStatus }
     *     
     */
    public ProvisioningStatus getProvisioningStatus() {
        return provisioningStatus;
    }

    /**
     * Sets the value of the provisioningStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProvisioningStatus }
     *     
     */
    public void setProvisioningStatus(ProvisioningStatus value) {
        this.provisioningStatus = value;
    }

    /**
     * Gets the value of the recordQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRecordQuantity() {
        return recordQuantity;
    }

    /**
     * Sets the value of the recordQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRecordQuantity(Integer value) {
        this.recordQuantity = value;
    }

    /**
     * Gets the value of the timeStampReceived property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimeStampReceived() {
        return timeStampReceived;
    }

    /**
     * Sets the value of the timeStampReceived property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimeStampReceived(XMLGregorianCalendar value) {
        this.timeStampReceived = value;
    }

}
