//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.08.09 at 07:25:26 PM ICT 
//


package com.mt.pos.ws.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for simManufacturePgp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="simManufacturePgp">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="idPgpKey" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="pgpKeyDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="pgpKeyName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="pgpKeyValue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="simManufacture" type="{http://rm.isl.mt.com/}simManufacture" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "simManufacturePgp", namespace = "http://rm.isl.mt.com/", propOrder = {
    "idPgpKey",
    "pgpKeyDescription",
    "pgpKeyName",
    "pgpKeyValue",
    "simManufacture"
})
public class SimManufacturePgp {

    protected Integer idPgpKey;
    protected String pgpKeyDescription;
    protected String pgpKeyName;
    protected String pgpKeyValue;
    protected SimManufacture simManufacture;

    /**
     * Gets the value of the idPgpKey property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getIdPgpKey() {
        return idPgpKey;
    }

    /**
     * Sets the value of the idPgpKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setIdPgpKey(Integer value) {
        this.idPgpKey = value;
    }

    /**
     * Gets the value of the pgpKeyDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPgpKeyDescription() {
        return pgpKeyDescription;
    }

    /**
     * Sets the value of the pgpKeyDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPgpKeyDescription(String value) {
        this.pgpKeyDescription = value;
    }

    /**
     * Gets the value of the pgpKeyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPgpKeyName() {
        return pgpKeyName;
    }

    /**
     * Sets the value of the pgpKeyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPgpKeyName(String value) {
        this.pgpKeyName = value;
    }

    /**
     * Gets the value of the pgpKeyValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPgpKeyValue() {
        return pgpKeyValue;
    }

    /**
     * Sets the value of the pgpKeyValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPgpKeyValue(String value) {
        this.pgpKeyValue = value;
    }

    /**
     * Gets the value of the simManufacture property.
     * 
     * @return
     *     possible object is
     *     {@link SimManufacture }
     *     
     */
    public SimManufacture getSimManufacture() {
        return simManufacture;
    }

    /**
     * Sets the value of the simManufacture property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimManufacture }
     *     
     */
    public void setSimManufacture(SimManufacture value) {
        this.simManufacture = value;
    }

}
