//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.08.09 at 07:25:26 PM ICT 
//


package com.mt.pos.ws.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for simOutputDataPK complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="simOutputDataPK">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="idCompany" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="idSimIcc" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "simOutputDataPK", namespace = "http://rm.isl.mt.com/", propOrder = {
    "idCompany",
    "idSimIcc"
})
public class SimOutputDataPK {

    protected long idCompany;
    protected Long idSimIcc;

    /**
     * Gets the value of the idCompany property.
     * 
     */
    public long getIdCompany() {
        return idCompany;
    }

    /**
     * Sets the value of the idCompany property.
     * 
     */
    public void setIdCompany(long value) {
        this.idCompany = value;
    }

    /**
     * Gets the value of the idSimIcc property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getIdSimIcc() {
        return idSimIcc;
    }

    /**
     * Sets the value of the idSimIcc property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setIdSimIcc(Long value) {
        this.idSimIcc = value;
    }

}
