//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.08.09 at 07:25:26 PM ICT 
//


package com.mt.pos.ws.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for simOutputData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="simOutputData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="company" type="{http://rm.isl.mt.com/}company" minOccurs="0"/>
 *         &lt;element name="orderOutputFile" type="{http://rm.isl.mt.com/}orderOutputFile" minOccurs="0"/>
 *         &lt;element name="provisioningStatus" type="{http://rm.isl.mt.com/}provisioningStatus" minOccurs="0"/>
 *         &lt;element name="simAdm1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="simAdm1Count" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="simAdm2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="simAdm3" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="simAdm4" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="simChv1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="simChv1Count" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="simChv2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="simChv2Count" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="simChv3" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="simChv3Count" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="simChv4" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="simChv4Count" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="simKi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="simOtaKey1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="simOtaKey2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="simOutputDataPK" type="{http://rm.isl.mt.com/}simOutputDataPK" minOccurs="0"/>
 *         &lt;element name="simPin1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="simPin2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="simPuk1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="simPuk2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="simRecordData" type="{http://rm.isl.mt.com/}simRecordData" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "simOutputData", namespace = "http://rm.isl.mt.com/", propOrder = {
    "company",
    "orderOutputFile",
    "provisioningStatus",
    "simAdm1",
    "simAdm1Count",
    "simAdm2",
    "simAdm3",
    "simAdm4",
    "simChv1",
    "simChv1Count",
    "simChv2",
    "simChv2Count",
    "simChv3",
    "simChv3Count",
    "simChv4",
    "simChv4Count",
    "simKi",
    "simOtaKey1",
    "simOtaKey2",
    "simOutputDataPK",
    "simPin1",
    "simPin2",
    "simPuk1",
    "simPuk2",
    "simRecordData"
})
public class SimOutputData {

    protected Company company;
    protected OrderOutputFile orderOutputFile;
    protected ProvisioningStatus provisioningStatus;
    protected String simAdm1;
    protected Integer simAdm1Count;
    protected String simAdm2;
    protected String simAdm3;
    protected String simAdm4;
    protected String simChv1;
    protected Integer simChv1Count;
    protected String simChv2;
    protected Integer simChv2Count;
    protected String simChv3;
    protected Integer simChv3Count;
    protected String simChv4;
    protected Integer simChv4Count;
    protected String simKi;
    protected String simOtaKey1;
    protected String simOtaKey2;
    protected SimOutputDataPK simOutputDataPK;
    protected String simPin1;
    protected String simPin2;
    protected String simPuk1;
    protected String simPuk2;
    protected SimRecordData simRecordData;

    /**
     * Gets the value of the company property.
     * 
     * @return
     *     possible object is
     *     {@link Company }
     *     
     */
    public Company getCompany() {
        return company;
    }

    /**
     * Sets the value of the company property.
     * 
     * @param value
     *     allowed object is
     *     {@link Company }
     *     
     */
    public void setCompany(Company value) {
        this.company = value;
    }

    /**
     * Gets the value of the orderOutputFile property.
     * 
     * @return
     *     possible object is
     *     {@link OrderOutputFile }
     *     
     */
    public OrderOutputFile getOrderOutputFile() {
        return orderOutputFile;
    }

    /**
     * Sets the value of the orderOutputFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderOutputFile }
     *     
     */
    public void setOrderOutputFile(OrderOutputFile value) {
        this.orderOutputFile = value;
    }

    /**
     * Gets the value of the provisioningStatus property.
     * 
     * @return
     *     possible object is
     *     {@link ProvisioningStatus }
     *     
     */
    public ProvisioningStatus getProvisioningStatus() {
        return provisioningStatus;
    }

    /**
     * Sets the value of the provisioningStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProvisioningStatus }
     *     
     */
    public void setProvisioningStatus(ProvisioningStatus value) {
        this.provisioningStatus = value;
    }

    /**
     * Gets the value of the simAdm1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSimAdm1() {
        return simAdm1;
    }

    /**
     * Sets the value of the simAdm1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSimAdm1(String value) {
        this.simAdm1 = value;
    }

    /**
     * Gets the value of the simAdm1Count property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSimAdm1Count() {
        return simAdm1Count;
    }

    /**
     * Sets the value of the simAdm1Count property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSimAdm1Count(Integer value) {
        this.simAdm1Count = value;
    }

    /**
     * Gets the value of the simAdm2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSimAdm2() {
        return simAdm2;
    }

    /**
     * Sets the value of the simAdm2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSimAdm2(String value) {
        this.simAdm2 = value;
    }

    /**
     * Gets the value of the simAdm3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSimAdm3() {
        return simAdm3;
    }

    /**
     * Sets the value of the simAdm3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSimAdm3(String value) {
        this.simAdm3 = value;
    }

    /**
     * Gets the value of the simAdm4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSimAdm4() {
        return simAdm4;
    }

    /**
     * Sets the value of the simAdm4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSimAdm4(String value) {
        this.simAdm4 = value;
    }

    /**
     * Gets the value of the simChv1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSimChv1() {
        return simChv1;
    }

    /**
     * Sets the value of the simChv1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSimChv1(String value) {
        this.simChv1 = value;
    }

    /**
     * Gets the value of the simChv1Count property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSimChv1Count() {
        return simChv1Count;
    }

    /**
     * Sets the value of the simChv1Count property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSimChv1Count(Integer value) {
        this.simChv1Count = value;
    }

    /**
     * Gets the value of the simChv2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSimChv2() {
        return simChv2;
    }

    /**
     * Sets the value of the simChv2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSimChv2(String value) {
        this.simChv2 = value;
    }

    /**
     * Gets the value of the simChv2Count property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSimChv2Count() {
        return simChv2Count;
    }

    /**
     * Sets the value of the simChv2Count property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSimChv2Count(Integer value) {
        this.simChv2Count = value;
    }

    /**
     * Gets the value of the simChv3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSimChv3() {
        return simChv3;
    }

    /**
     * Sets the value of the simChv3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSimChv3(String value) {
        this.simChv3 = value;
    }

    /**
     * Gets the value of the simChv3Count property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSimChv3Count() {
        return simChv3Count;
    }

    /**
     * Sets the value of the simChv3Count property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSimChv3Count(Integer value) {
        this.simChv3Count = value;
    }

    /**
     * Gets the value of the simChv4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSimChv4() {
        return simChv4;
    }

    /**
     * Sets the value of the simChv4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSimChv4(String value) {
        this.simChv4 = value;
    }

    /**
     * Gets the value of the simChv4Count property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSimChv4Count() {
        return simChv4Count;
    }

    /**
     * Sets the value of the simChv4Count property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSimChv4Count(Integer value) {
        this.simChv4Count = value;
    }

    /**
     * Gets the value of the simKi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSimKi() {
        return simKi;
    }

    /**
     * Sets the value of the simKi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSimKi(String value) {
        this.simKi = value;
    }

    /**
     * Gets the value of the simOtaKey1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSimOtaKey1() {
        return simOtaKey1;
    }

    /**
     * Sets the value of the simOtaKey1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSimOtaKey1(String value) {
        this.simOtaKey1 = value;
    }

    /**
     * Gets the value of the simOtaKey2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSimOtaKey2() {
        return simOtaKey2;
    }

    /**
     * Sets the value of the simOtaKey2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSimOtaKey2(String value) {
        this.simOtaKey2 = value;
    }

    /**
     * Gets the value of the simOutputDataPK property.
     * 
     * @return
     *     possible object is
     *     {@link SimOutputDataPK }
     *     
     */
    public SimOutputDataPK getSimOutputDataPK() {
        return simOutputDataPK;
    }

    /**
     * Sets the value of the simOutputDataPK property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimOutputDataPK }
     *     
     */
    public void setSimOutputDataPK(SimOutputDataPK value) {
        this.simOutputDataPK = value;
    }

    /**
     * Gets the value of the simPin1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSimPin1() {
        return simPin1;
    }

    /**
     * Sets the value of the simPin1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSimPin1(String value) {
        this.simPin1 = value;
    }

    /**
     * Gets the value of the simPin2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSimPin2() {
        return simPin2;
    }

    /**
     * Sets the value of the simPin2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSimPin2(String value) {
        this.simPin2 = value;
    }

    /**
     * Gets the value of the simPuk1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSimPuk1() {
        return simPuk1;
    }

    /**
     * Sets the value of the simPuk1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSimPuk1(String value) {
        this.simPuk1 = value;
    }

    /**
     * Gets the value of the simPuk2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSimPuk2() {
        return simPuk2;
    }

    /**
     * Sets the value of the simPuk2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSimPuk2(String value) {
        this.simPuk2 = value;
    }

    /**
     * Gets the value of the simRecordData property.
     * 
     * @return
     *     possible object is
     *     {@link SimRecordData }
     *     
     */
    public SimRecordData getSimRecordData() {
        return simRecordData;
    }

    /**
     * Sets the value of the simRecordData property.
     * 
     * @param value
     *     allowed object is
     *     {@link SimRecordData }
     *     
     */
    public void setSimRecordData(SimRecordData value) {
        this.simRecordData = value;
    }

}
