//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.08.09 at 07:25:26 PM ICT 
//


package com.mt.pos.ws.beans;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for simProduct complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="simProduct">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="company" type="{http://rm.isl.mt.com/}company" minOccurs="0"/>
 *         &lt;element name="idSimProduct" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="idWhitePaper" type="{http://rm.isl.mt.com/}whitePaper" minOccurs="0"/>
 *         &lt;element name="profile" type="{http://rm.isl.mt.com/}profile" minOccurs="0"/>
 *         &lt;element name="simManufactureCollection" type="{http://rm.isl.mt.com/}simManufacture" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="simProductDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="simProductName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="simProductVersionNumber" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "simProduct", namespace = "http://rm.isl.mt.com/", propOrder = {
    "company",
    "idSimProduct",
    "idWhitePaper",
    "profile",
    "simManufactureCollections",
    "simProductDescription",
    "simProductName",
    "simProductVersionNumber"
})
public class SimProduct {

    protected Company company;
    protected Integer idSimProduct;
    protected WhitePaper idWhitePaper;
    protected Profile profile;
    @XmlElement(name = "simManufactureCollection", nillable = true)
    protected List<SimManufacture> simManufactureCollections;
    protected String simProductDescription;
    protected String simProductName;
    protected Long simProductVersionNumber;

    /**
     * Gets the value of the company property.
     * 
     * @return
     *     possible object is
     *     {@link Company }
     *     
     */
    public Company getCompany() {
        return company;
    }

    /**
     * Sets the value of the company property.
     * 
     * @param value
     *     allowed object is
     *     {@link Company }
     *     
     */
    public void setCompany(Company value) {
        this.company = value;
    }

    /**
     * Gets the value of the idSimProduct property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getIdSimProduct() {
        return idSimProduct;
    }

    /**
     * Sets the value of the idSimProduct property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setIdSimProduct(Integer value) {
        this.idSimProduct = value;
    }

    /**
     * Gets the value of the idWhitePaper property.
     * 
     * @return
     *     possible object is
     *     {@link WhitePaper }
     *     
     */
    public WhitePaper getIdWhitePaper() {
        return idWhitePaper;
    }

    /**
     * Sets the value of the idWhitePaper property.
     * 
     * @param value
     *     allowed object is
     *     {@link WhitePaper }
     *     
     */
    public void setIdWhitePaper(WhitePaper value) {
        this.idWhitePaper = value;
    }

    /**
     * Gets the value of the profile property.
     * 
     * @return
     *     possible object is
     *     {@link Profile }
     *     
     */
    public Profile getProfile() {
        return profile;
    }

    /**
     * Sets the value of the profile property.
     * 
     * @param value
     *     allowed object is
     *     {@link Profile }
     *     
     */
    public void setProfile(Profile value) {
        this.profile = value;
    }

    /**
     * Gets the value of the simManufactureCollections property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the simManufactureCollections property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSimManufactureCollections().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SimManufacture }
     * 
     * 
     */
    public List<SimManufacture> getSimManufactureCollections() {
        if (simManufactureCollections == null) {
            simManufactureCollections = new ArrayList<SimManufacture>();
        }
        return this.simManufactureCollections;
    }

    /**
     * Gets the value of the simProductDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSimProductDescription() {
        return simProductDescription;
    }

    /**
     * Sets the value of the simProductDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSimProductDescription(String value) {
        this.simProductDescription = value;
    }

    /**
     * Gets the value of the simProductName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSimProductName() {
        return simProductName;
    }

    /**
     * Sets the value of the simProductName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSimProductName(String value) {
        this.simProductName = value;
    }

    /**
     * Gets the value of the simProductVersionNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getSimProductVersionNumber() {
        return simProductVersionNumber;
    }

    /**
     * Sets the value of the simProductVersionNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setSimProductVersionNumber(Long value) {
        this.simProductVersionNumber = value;
    }

}
