//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.08.09 at 07:25:26 PM ICT 
//


package com.mt.pos.ws.beans;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for whitePaper complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="whitePaper">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="createdDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="electricalProfileConllection" type="{http://rm.isl.mt.com/}electricalProfile" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="graphicalProfileCollection" type="{http://rm.isl.mt.com/}graphicalProfile" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="idWhitePaper" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="updatedDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="whitePaperContentType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="whitePaperData" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/>
 *         &lt;element name="whitePaperDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="whitePaperName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "whitePaper", namespace = "http://rm.isl.mt.com/", propOrder = {
    "createdDateTime",
    "electricalProfileConllections",
    "graphicalProfileCollections",
    "idWhitePaper",
    "updatedDateTime",
    "whitePaperContentType",
    "whitePaperData",
    "whitePaperDescription",
    "whitePaperName"
})
public class WhitePaper {

    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar createdDateTime;
    @XmlElement(name = "electricalProfileConllection", nillable = true)
    protected List<ElectricalProfile> electricalProfileConllections;
    @XmlElement(name = "graphicalProfileCollection", nillable = true)
    protected List<GraphicalProfile> graphicalProfileCollections;
    protected Integer idWhitePaper;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar updatedDateTime;
    protected String whitePaperContentType;
    protected byte[] whitePaperData;
    protected String whitePaperDescription;
    protected String whitePaperName;

    /**
     * Gets the value of the createdDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreatedDateTime() {
        return createdDateTime;
    }

    /**
     * Sets the value of the createdDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreatedDateTime(XMLGregorianCalendar value) {
        this.createdDateTime = value;
    }

    /**
     * Gets the value of the electricalProfileConllections property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the electricalProfileConllections property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getElectricalProfileConllections().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ElectricalProfile }
     * 
     * 
     */
    public List<ElectricalProfile> getElectricalProfileConllections() {
        if (electricalProfileConllections == null) {
            electricalProfileConllections = new ArrayList<ElectricalProfile>();
        }
        return this.electricalProfileConllections;
    }

    /**
     * Gets the value of the graphicalProfileCollections property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the graphicalProfileCollections property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGraphicalProfileCollections().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GraphicalProfile }
     * 
     * 
     */
    public List<GraphicalProfile> getGraphicalProfileCollections() {
        if (graphicalProfileCollections == null) {
            graphicalProfileCollections = new ArrayList<GraphicalProfile>();
        }
        return this.graphicalProfileCollections;
    }

    /**
     * Gets the value of the idWhitePaper property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getIdWhitePaper() {
        return idWhitePaper;
    }

    /**
     * Sets the value of the idWhitePaper property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setIdWhitePaper(Integer value) {
        this.idWhitePaper = value;
    }

    /**
     * Gets the value of the updatedDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getUpdatedDateTime() {
        return updatedDateTime;
    }

    /**
     * Sets the value of the updatedDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setUpdatedDateTime(XMLGregorianCalendar value) {
        this.updatedDateTime = value;
    }

    /**
     * Gets the value of the whitePaperContentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWhitePaperContentType() {
        return whitePaperContentType;
    }

    /**
     * Sets the value of the whitePaperContentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWhitePaperContentType(String value) {
        this.whitePaperContentType = value;
    }

    /**
     * Gets the value of the whitePaperData property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getWhitePaperData() {
        return whitePaperData;
    }

    /**
     * Sets the value of the whitePaperData property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setWhitePaperData(byte[] value) {
        this.whitePaperData = ((byte[]) value);
    }

    /**
     * Gets the value of the whitePaperDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWhitePaperDescription() {
        return whitePaperDescription;
    }

    /**
     * Sets the value of the whitePaperDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWhitePaperDescription(String value) {
        this.whitePaperDescription = value;
    }

    /**
     * Gets the value of the whitePaperName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWhitePaperName() {
        return whitePaperName;
    }

    /**
     * Sets the value of the whitePaperName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWhitePaperName(String value) {
        this.whitePaperName = value;
    }

}
