//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.01 at 12:57:22 PM ICT 
//


package com.itap.ebms.resp;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MessageHeader" maxOccurs="5000">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="MessageType">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="10"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="UserID">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="17"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="Timestamp" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                   &lt;element name="MessageDetail">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;choice>
 *                             &lt;element ref="{http://ebxml.customs.go.th/schema/LicenseResponse_2_0}LicenseAccept"/>
 *                             &lt;element ref="{http://ebxml.customs.go.th/schema/LicenseResponse_2_0}LicenseReject"/>
 *                             &lt;element ref="{http://ebxml.customs.go.th/schema/LicenseResponse_2_0}BOIAccept"/>
 *                             &lt;element ref="{http://ebxml.customs.go.th/schema/LicenseResponse_2_0}BOIReject"/>
 *                           &lt;/choice>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://www.w3.org/2000/09/xmldsig#}Signature" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "messageHeaders",
    "signatures"
})
@XmlRootElement(name = "LicenseResponse", namespace = "http://ebxml.customs.go.th/schema/LicenseResponse_2_0")
public class LicenseResponse {

    @XmlElement(name = "MessageHeader", required = true)
    protected List<LicenseResponse.MessageHeader> messageHeaders;
    @XmlElement(name = "Signature", namespace = "http://www.w3.org/2000/09/xmldsig#")
    protected List<Signature> signatures;

    /**
     * Gets the value of the messageHeaders property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the messageHeaders property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMessageHeaders().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LicenseResponse.MessageHeader }
     * 
     * 
     */
    public List<LicenseResponse.MessageHeader> getMessageHeaders() {
        if (messageHeaders == null) {
            messageHeaders = new ArrayList<LicenseResponse.MessageHeader>();
        }
        return this.messageHeaders;
    }

    /**
     * Gets the value of the signatures property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the signatures property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSignatures().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Signature }
     * 
     * 
     */
    public List<Signature> getSignatures() {
        if (signatures == null) {
            signatures = new ArrayList<Signature>();
        }
        return this.signatures;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="MessageType">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="10"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="UserID">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="17"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="Timestamp" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *         &lt;element name="MessageDetail">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;choice>
     *                   &lt;element ref="{http://ebxml.customs.go.th/schema/LicenseResponse_2_0}LicenseAccept"/>
     *                   &lt;element ref="{http://ebxml.customs.go.th/schema/LicenseResponse_2_0}LicenseReject"/>
     *                   &lt;element ref="{http://ebxml.customs.go.th/schema/LicenseResponse_2_0}BOIAccept"/>
     *                   &lt;element ref="{http://ebxml.customs.go.th/schema/LicenseResponse_2_0}BOIReject"/>
     *                 &lt;/choice>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "messageType",
        "userID",
        "timestamp",
        "messageDetail"
    })
    public static class MessageHeader {

        @XmlElement(name = "MessageType", required = true)
        protected String messageType;
        @XmlElement(name = "UserID", required = true)
        protected String userID;
        @XmlElement(name = "Timestamp", required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar timestamp;
        @XmlElement(name = "MessageDetail", required = true)
        protected LicenseResponse.MessageHeader.MessageDetail messageDetail;

        /**
         * Gets the value of the messageType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMessageType() {
            return messageType;
        }

        /**
         * Sets the value of the messageType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMessageType(String value) {
            this.messageType = value;
        }

        /**
         * Gets the value of the userID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUserID() {
            return userID;
        }

        /**
         * Sets the value of the userID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUserID(String value) {
            this.userID = value;
        }

        /**
         * Gets the value of the timestamp property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getTimestamp() {
            return timestamp;
        }

        /**
         * Sets the value of the timestamp property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setTimestamp(XMLGregorianCalendar value) {
            this.timestamp = value;
        }

        /**
         * Gets the value of the messageDetail property.
         * 
         * @return
         *     possible object is
         *     {@link LicenseResponse.MessageHeader.MessageDetail }
         *     
         */
        public LicenseResponse.MessageHeader.MessageDetail getMessageDetail() {
            return messageDetail;
        }

        /**
         * Sets the value of the messageDetail property.
         * 
         * @param value
         *     allowed object is
         *     {@link LicenseResponse.MessageHeader.MessageDetail }
         *     
         */
        public void setMessageDetail(LicenseResponse.MessageHeader.MessageDetail value) {
            this.messageDetail = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;choice>
         *         &lt;element ref="{http://ebxml.customs.go.th/schema/LicenseResponse_2_0}LicenseAccept"/>
         *         &lt;element ref="{http://ebxml.customs.go.th/schema/LicenseResponse_2_0}LicenseReject"/>
         *         &lt;element ref="{http://ebxml.customs.go.th/schema/LicenseResponse_2_0}BOIAccept"/>
         *         &lt;element ref="{http://ebxml.customs.go.th/schema/LicenseResponse_2_0}BOIReject"/>
         *       &lt;/choice>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "boiReject",
            "boiAccept",
            "licenseReject",
            "licenseAccept"
        })
        public static class MessageDetail {

            @XmlElement(name = "BOIReject", namespace = "http://ebxml.customs.go.th/schema/LicenseResponse_2_0")
            protected BOIReject boiReject;
            @XmlElement(name = "BOIAccept", namespace = "http://ebxml.customs.go.th/schema/LicenseResponse_2_0")
            protected BOIAccept boiAccept;
            @XmlElement(name = "LicenseReject", namespace = "http://ebxml.customs.go.th/schema/LicenseResponse_2_0")
            protected LicenseReject licenseReject;
            @XmlElement(name = "LicenseAccept", namespace = "http://ebxml.customs.go.th/schema/LicenseResponse_2_0")
            protected LicenseAccept licenseAccept;

            /**
             * Gets the value of the boiReject property.
             * 
             * @return
             *     possible object is
             *     {@link BOIReject }
             *     
             */
            public BOIReject getBOIReject() {
                return boiReject;
            }

            /**
             * Sets the value of the boiReject property.
             * 
             * @param value
             *     allowed object is
             *     {@link BOIReject }
             *     
             */
            public void setBOIReject(BOIReject value) {
                this.boiReject = value;
            }

            /**
             * Gets the value of the boiAccept property.
             * 
             * @return
             *     possible object is
             *     {@link BOIAccept }
             *     
             */
            public BOIAccept getBOIAccept() {
                return boiAccept;
            }

            /**
             * Sets the value of the boiAccept property.
             * 
             * @param value
             *     allowed object is
             *     {@link BOIAccept }
             *     
             */
            public void setBOIAccept(BOIAccept value) {
                this.boiAccept = value;
            }

            /**
             * Gets the value of the licenseReject property.
             * 
             * @return
             *     possible object is
             *     {@link LicenseReject }
             *     
             */
            public LicenseReject getLicenseReject() {
                return licenseReject;
            }

            /**
             * Sets the value of the licenseReject property.
             * 
             * @param value
             *     allowed object is
             *     {@link LicenseReject }
             *     
             */
            public void setLicenseReject(LicenseReject value) {
                this.licenseReject = value;
            }

            /**
             * Gets the value of the licenseAccept property.
             * 
             * @return
             *     possible object is
             *     {@link LicenseAccept }
             *     
             */
            public LicenseAccept getLicenseAccept() {
                return licenseAccept;
            }

            /**
             * Sets the value of the licenseAccept property.
             * 
             * @param value
             *     allowed object is
             *     {@link LicenseAccept }
             *     
             */
            public void setLicenseAccept(LicenseAccept value) {
                this.licenseAccept = value;
            }

        }

    }

}
